addons:
  postgresql: 10
  apt:
    package:
      - postgresql-10
      - postgresql-client-10
env:
  global:
  - PGPORT=5433

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database coax_currency_ci_test;' -U postgres

dist: trusty

language: ruby

rvm:
  - 2.5.1

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
